# The current version of the modpack installed. Required
version = "1.0.0"

# The name of the modpack. Required
modpackName = ""

# The URL of the update host server. Required
hostUrl = ""

# The maximum number of concurrent downloads allowed.
maxParallelDownloads = 5
