# The current version of the modpack installed. Required
version = "1.0.0"

# The name of the modpack. Required
modpackName = ""

# The URL of the version data file. Required
versionDataUrl = ""

# The maximum number of concurrent downloads allowed.
maxParallelDownloads = 5
